# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{twitter2campfire}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["James Golick"]
  s.date = %q{2009-12-15}
  s.default_executable = %q{twitter2campfire}
  s.description = %q{found this code here: [http://github.com/paulca/twitter2campfire]. I just gemified it.}
  s.email = %q{james@giraffesoft.ca}
  s.executables = ["twitter2campfire"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "README",
     "Rakefile",
     "VERSION",
     "bin/twitter2campfire",
     "examples/archived_latest.txt",
     "examples/config.yml",
     "fixtures/sample.xml",
     "fixtures/test_blank_cachefile.txt",
     "fixtures/test_cachefile.txt",
     "lib/twitter2campfire.rb",
     "lib/twitter2campfire/cli.rb",
     "spec/twitter2campfire_spec.rb"
  ]
  s.homepage = %q{http://github.com/giraffesoft/twitter2campfire}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{gemification of twitter2campfire script}
  s.test_files = [
    "spec/twitter2campfire_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<rio>, [">= 0"])
      s.add_runtime_dependency(%q<tinder>, [">= 0"])
      s.add_runtime_dependency(%q<hpricot>, [">= 0"])
      s.add_runtime_dependency(%q<htmlentities>, [">= 0"])
      s.add_runtime_dependency(%q<thor>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<rio>, [">= 0"])
      s.add_dependency(%q<tinder>, [">= 0"])
      s.add_dependency(%q<hpricot>, [">= 0"])
      s.add_dependency(%q<htmlentities>, [">= 0"])
      s.add_dependency(%q<thor>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<rio>, [">= 0"])
    s.add_dependency(%q<tinder>, [">= 0"])
    s.add_dependency(%q<hpricot>, [">= 0"])
    s.add_dependency(%q<htmlentities>, [">= 0"])
    s.add_dependency(%q<thor>, [">= 0"])
  end
end

